### ISSUE TITLE
使用后它将.vue文件每一行的下面都加了一个空行

### ISSUE THREAD

**Issue by shijiansu** [peakchen90/vue-beautify#11]
如题. 需要配置什么吗, 谢谢!

**Comment by refanbanzhang** [comment]
我也是这个问题，这个插件真是垃圾到不行，连说明都没有

**Comment by sandmanman** [comment]
同入坑了。。。。。

**Comment by peakchen90** [comment]
@shijiansu @gaoqiang19514 @sandmanman  I am sorry, this extension is no longer updated, please install vetur, which is a better extension of vue.
