### ISSUE TITLE
template 里嵌套 template匹配错误

### ISSUE THREAD

**Issue by GuihaiHU** [peakchen90/vue-beautify#13]
在template中嵌套另一个template，无法自动配对template，所有闭合标签都与第一个对其

**Comment by XieShangxu** [comment]
+1

**Comment by shannonliang312** [comment]
+1

**Comment by pierre50** [comment]
+1

**Comment by misaya** [comment]
+1    比如使用ElementUI时, 自定义单元格需要<template scope></template> 标签, 这个会缩进到左. 非配对.

**Comment by peakchen90** [comment]
@GuihaiHU @XieShangxu @shannonliang312 @pierre50 @duotai  I am sorry, this extension is no longer updated, please install vetur, which is a better extension of vue.
