### ISSUE TITLE
Newline on every line

### ISSUE THREAD

**Issue by ghost** [peakchen90/vue-beautify#16]
When I beautify my file, there is one line added after every line.
![before](https://cloud.githubusercontent.com/assets/25482680/24764524/e72f6090-1af4-11e7-9bec-0adaff2b2811.PNG)
![after](https://cloud.githubusercontent.com/assets/25482680/24764525/e73243a0-1af4-11e7-9b37-6eaf335f29cc.PNG)

**Comment by Apelsinmack** [comment]
I experiencing the same bug. As a workaround I changed the PC line endings to UNIX line endings and now it's working. Still very annoying though because I need to do it everytime I create a new file.

**Comment by peakchen90** [comment]
@tstosius  @KenQQQ  I am sorry, this extension is no longer updated, please install vetur, which is a better extension of vue.
