### ISSUE TITLE
反复点击美化会一直加行间距

### ISSUE THREAD

**Issue by ghost** [peakchen90/vue-beautify#17]
![2017-05-27_101926](https://cloud.githubusercontent.com/assets/23623945/26517186/018eab82-42c6-11e7-9c0f-c2363477c7d4.png)

**Comment by DayangLee** [comment]
我这儿也出现同样的问题

**Comment by songhejia** [comment]
我这也是同样问题

**Comment by peakchen90** [comment]
@lintscc @DayangLee @songhejia  I am sorry, this extension is no longer updated, please install vetur, which is a better extension of vue.
