### ISSUE TITLE
What theme are you using in the screenshot gif ? 

### ISSUE THREAD

**Issue by romans127** [peakchen90/vue-beautify#2]
Greetings, what theme are you using in your editor for the screenshot gif ?

**Comment by peakchen90** [comment]
@rwatts3  it's `One Dark Theme`
![image](https://cloud.githubusercontent.com/assets/17677589/24134660/a9d6c884-0e40-11e7-8b3e-9f7deb890725.png)

**Comment by romans127** [comment]
Thank you
