### ISSUE TITLE
bug: 注释部分格式混乱

### ISSUE THREAD

**Issue by lxoxo00a** [peakchen90/vue-beautify#21]
最初的注释是这样的：
![image](https://user-images.githubusercontent.com/22574711/35951138-0d4d63aa-0cb5-11e8-8e99-efc71794c6bf.png)
第一次 Ctrl+Shift+6后：
![image](https://user-images.githubusercontent.com/22574711/35951153-1dba6f80-0cb5-11e8-834f-59146d1594db.png)
第二次 Ctrl+Shift+6：
![image](https://user-images.githubusercontent.com/22574711/35951166-295c56d2-0cb5-11e8-8d69-8f0df7a335ef.png)
第三次：
![image](https://user-images.githubusercontent.com/22574711/35951173-333e8256-0cb5-11e8-9eb2-6cf79f996c49.png)
第n次：
![image](https://user-images.githubusercontent.com/22574711/35951183-3c86b04a-0cb5-11e8-8083-67c8c4e35136.png)

**Comment by lxoxo00a** [comment]
先卸载了，有机会的话试试参与一下

**Comment by peakchen90** [comment]
@JkVon 抱歉，其实这个项目很久之前就不再维护了，可以看下 README，因为有一个更好的插件 vetur，推荐你使用下
