### ISSUE TITLE
覆盖了原生的beautify

### ISSUE THREAD

**Issue by HADB** [peakchen90/vue-beautify#4]
将editor.action.formatDocument和vueBeautify.format都设置同一个快捷键之后，在非vue的文件里面，原来的formatDocument不起作用了

**Comment by peakchen90** [comment]
@HADB  请更新版本后，将快捷键映射重新复制过来

**Comment by HADB** [comment]
赞！其实我现在就是手动加了个resourceLangId=='vue'  😃
