### ISSUE TITLE
It does not work as expected in inner <template> tags.

### ISSUE THREAD

**Issue by safaorhan** [peakchen90/vue-beautify#6]
Steps to reproduce:

- Create a .vue file.
- Put the code below:

```
<template>
    <template class="buggy"></template>
</template>
```

- Beautify Vue (Shift + Cmd + F)

**Expected:**
```
<template>
    <template class="buggy"></template>
</template>
````

**Actual:**
```
<template>
    <template class="buggy">
</template>

</template>
```

**Comment by HADB** [comment]
👍 I found this problem as well. 这个问题我也发现了。

**Comment by peakchen90** [comment]
@safaorhan It seems not to work when you execute `Beautify Vue` multiple times.
Maybe the [vetur](https://marketplace.visualstudio.com/items?itemName=octref.vetur) is a better choice.

**Comment by safaorhan** [comment]
@peakchen90 Thanks for the suggestion. I will look at it.

Also can you look at the pull request: https://github.com/peakchen90/vue-beautify/pull/7

**Comment by yoyo837** [comment]
@peakchen90 You seem too busy, no time to maintain this project, maybe you need some teammates to help you.
